import type { Metadata } from "next";

import "@mantine/dates/styles.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/carousel/styles.css";
import "./globals.css";
import "dayjs/locale/de";
import "dayjs/locale/en";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ClerkProvider } from "@clerk/nextjs";
import { deDE, enUS } from "@clerk/localizations";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { theme } from "@lib/theme";
import dynamic from "next/dynamic";
import { Providers } from "@providers/providers";
import { DatesProvider } from "@mantine/dates";

const PostHogPageView = dynamic(() => import("@providers/post-hog-provider"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <ClerkProvider localization={locale === "de" ? deDE : enUS}>
      <Providers>
        <PostHogPageView />
        <NextIntlClientProvider messages={messages}>
          <html lang={locale}>
            <head>
              <ColorSchemeScript />
            </head>
            <body>
              <MantineProvider theme={theme}>
                <Notifications />
                {children}
              </MantineProvider>
            </body>
          </html>
        </NextIntlClientProvider>
      </Providers>
    </ClerkProvider>
  );
}
